name: cus_icon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/vk_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/vk_icon.png
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
